pipeline{
  agent any
  stages{
    stage ('checkout'){
      steps{
        checkout scm
      }
    }
    stage ('Bucket Create'){
      steps{
        sh 'aws s3api create-bucket --bucket my-bucket-ravi-1234 --region us-east-1'
      }
    }
  }
//    stage ('Build'){
//        parallel {
//              stage("Angular Build") {
                  
//                   steps {
//                          echo Installing packages
//                          npm install
//                          npm install -g @angular/cli@8
//                          echo Building Angular Project
//                          ng build
//                   }
//              }
//               stage("S3 Build") {
//                   steps {
//                          //aws cloudformation create-stack --stack-name S3bucketcreation --template-body file:cft.yaml
//                          aws s3api creat-bucket --bucket angular-demo-bucket --region us-east-1
//                   }
//               }
//        }
//    }
//     stage ('Deploy'){
//       steps{
//         aws s3 cp dist/ s3://AngularS3Bucket/ --recursive --region us-east-1
//       }
//     }
}